# Generated by Django 3.2.9 on 2022-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_restaurant',
            fields=[
                ('Restaurant_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Photo', models.CharField(max_length=225)),
                ('Description', models.CharField(max_length=90)),
                ('Phone', models.CharField(max_length=90)),
                ('Email', models.CharField(max_length=90)),
                ('Status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_restaurant',
            },
        ),
    ]
