# Generated by Django 3.2.9 on 2022-09-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospital',
            fields=[
                ('Hospital_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=90)),
                ('District', models.CharField(max_length=90)),
                ('Pincode', models.CharField(max_length=90)),
                ('Phone', models.CharField(max_length=90)),
                ('Email', models.CharField(max_length=90)),
                ('Status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_hospital',
            },
        ),
    ]
