# Generated by Django 3.2.9 on 2022-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_tbl_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('Event_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=90)),
                ('Description', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=90)),
                ('Date', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_event',
            },
        ),
    ]
