# Generated by Django 3.2.9 on 2022-09-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_menu',
            fields=[
                ('Menu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Menu_name', models.CharField(max_length=90)),
                ('Description', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=90)),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=90)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.tbl_restaurant')),
            ],
            options={
                'db_table': 'tbl_menu',
            },
        ),
    ]
