# Generated by Django 3.2.9 on 2022-09-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_tbl_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_menu',
            old_name='restaurant_id',
            new_name='Restaurant_id',
        ),
    ]
