# Generated by Django 3.2.9 on 2022-09-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_rename_restaurant_id_tbl_menu_restaurant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('restaurant_id', models.IntegerField()),
                ('workshop_id', models.IntegerField()),
                ('Event_id', models.IntegerField()),
                ('Menu_id', models.IntegerField()),
            ],
            options={
                'db_table': 'id_gen',
            },
        ),
    ]
