# Generated by Django 3.2.9 on 2022-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_auto_20220911_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('Food_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Restaurant_name', models.CharField(max_length=100)),
                ('Speciality', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=90)),
                ('Location', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_food',
            },
        ),
    ]
