# Generated by Django 3.2.9 on 2022-09-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_id_gen_food_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('Location_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Location_name', models.CharField(max_length=90)),
                ('Photo', models.CharField(max_length=90)),
                ('Speciality', models.CharField(max_length=90)),
                ('Transportation', models.CharField(max_length=100)),
                ('Route', models.CharField(max_length=90)),
                ('Time_taken', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_location',
            },
        ),
    ]
