# Generated by Django 3.2.9 on 2022-09-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_tbl_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Location_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
