# Generated by Django 3.2.9 on 2022-09-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0013_id_gen_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_petrolpump',
            fields=[
                ('Pump_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Pump_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=90)),
                ('Phone', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_petrolpump',
            },
        ),
    ]
