# Generated by Django 3.2.9 on 2022-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0014_tbl_petrolpump'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Pump_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
