# Generated by Django 3.2.9 on 2022-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0016_tbl_taxistand'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Taxistand_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
