# Generated by Django 3.2.9 on 2022-09-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0017_id_gen_taxistand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_taxistand',
            old_name='Taxi_name',
            new_name='Name',
        ),
    ]
