# Generated by Django 3.2.9 on 2022-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_tbl_busstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Busstand_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
