# Generated by Django 3.2.9 on 2022-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0023_tbl_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Room_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
