# Generated by Django 3.2.9 on 2022-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0024_id_gen_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_traveller',
            fields=[
                ('Traveller_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=90)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_traveller',
            },
        ),
    ]
