# Generated by Django 3.2.9 on 2022-09-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0026_id_gen_traveller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('Review_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Review', models.CharField(max_length=90)),
                ('Photo', models.CharField(max_length=80)),
                ('Review_date', models.CharField(max_length=50)),
                ('Traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.tbl_traveller')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
