# Generated by Django 4.0.6 on 2022-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0029_tbl_food_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_restaurant',
            name='Website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_hospital',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_restaurant',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
