# Generated by Django 3.2.9 on 2022-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_tbl_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('Username', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
