# Generated by Django 3.2.9 on 2022-09-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_id_gen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id_gen',
            old_name='hospital_id',
            new_name='Hospital_id',
        ),
        migrations.RenameField(
            model_name='id_gen',
            old_name='restaurant_id',
            new_name='Restaurant_id',
        ),
        migrations.RenameField(
            model_name='id_gen',
            old_name='workshop_id',
            new_name='Workshop_id',
        ),
    ]
