# Generated by Django 3.2.9 on 2022-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0010_tbl_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Food_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
