# Generated by Django 3.2.9 on 2022-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0015_id_gen_pump_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_taxistand',
            fields=[
                ('Taxistand_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Taxi_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_taxistand',
            },
        ),
    ]
