# Generated by Django 3.2.9 on 2022-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0020_id_gen_busstand_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_lodge',
            fields=[
                ('Lodge_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_lodge',
            },
        ),
    ]
