# Generated by Django 3.2.9 on 2022-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0021_tbl_lodge'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Lodge_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
