# Generated by Django 3.2.9 on 2022-09-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0022_id_gen_lodge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_room',
            fields=[
                ('Room_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Room_type', models.CharField(max_length=50)),
                ('Rate', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=90)),
                ('Lodge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.tbl_lodge')),
            ],
            options={
                'db_table': 'tbl_room',
            },
        ),
    ]
