# Generated by Django 3.2.9 on 2022-09-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0025_tbl_traveller'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Traveller_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
