# Generated by Django 3.2.9 on 2022-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0027_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_gen',
            name='Review_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
