# Generated by Django 4.0.6 on 2022-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0030_tbl_restaurant_website_alter_tbl_hospital_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_restaurant',
            name='Website',
            field=models.CharField(max_length=100),
        ),
    ]
